[accounts.gmail]
email = "ahmednasr999@gmail.com"
display-name = "Ahmed Nasr"
default = true

# Gmail IMAP settings
backend.type = "imap"
backend.host = "imap.gmail.com"
backend.port = 993
backend.encryption.type = "tls"
backend.login = "ahmednasr999@gmail.com"
backend.auth.type = "password"
backend.auth.raw = "wvdklorwnunbyjir"

# Gmail SMTP settings  
message.send.backend.type = "smtp"
message.send.backend.host = "smtp.gmail.com"
message.send.backend.port = 587
message.send.backend.encryption.type = "start-tls"
message.send.backend.login = "ahmednasr999@gmail.com"
message.send.backend.auth.type = "password"
message.send.backend.auth.raw = "wvdklorwnunbyjir"