#!/usr/bin/env python3
"""Apply a brand proposal to a sandbox copy of the editorial showcase deck."""

from __future__ import annotations

import argparse
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SOURCE = ROOT / "examples" / "editorial-pattern-showcase"
DEFAULT_OUTPUT = ROOT / "examples" / "branded-showcase"


def extract_value(markdown: str, key: str) -> str:
    match = re.search(rf"^- {re.escape(key)}: `([^`]+)`$", markdown, flags=re.MULTILINE)
    if not match:
        raise SystemExit(f"Missing key {key!r} in proposal markdown")
    return match.group(1)


def replace_once(text: str, old: str, new: str, label: str) -> str:
    if old not in text:
        raise SystemExit(f"Could not find expected {label}: {old!r}")
    return text.replace(old, new, 1)


def apply_brand(source_dir: Path, output_dir: Path, proposal_path: Path, name: str) -> Path:
    if output_dir.exists():
        shutil.rmtree(output_dir)
    shutil.copytree(source_dir, output_dir)

    helpers_src = ROOT / 'assets' / 'pptxgenjs_helpers'
    helpers_dst = output_dir / 'pptxgenjs_helpers'
    if helpers_dst.exists():
        shutil.rmtree(helpers_dst)
    shutil.copytree(helpers_src, helpers_dst)

    proposal = proposal_path.read_text(encoding="utf-8")
    deck_path = output_dir / "deck.js"
    deck = deck_path.read_text(encoding="utf-8")

    bg = extract_value(proposal, "bg")
    surface = extract_value(proposal, "surface")
    surface_alt = extract_value(proposal, "surface-2")
    text_primary = extract_value(proposal, "text-primary")
    text_secondary = extract_value(proposal, "text-secondary")
    text_soft = extract_value(proposal, "text-soft")
    rule = extract_value(proposal, "rule")
    accent = extract_value(proposal, "accent")
    accent_soft = extract_value(proposal, "accent-soft")
    data_link = extract_value(proposal, "data-link")

    display_font = extract_value(proposal, "display")
    body_font = extract_value(proposal, "body")

    replacements = {
        "pptx.subject = 'Slides editorial pattern showcase';": f"pptx.subject = '{name} branded showcase';",
        "pptx.title = 'Slides Editorial Pattern Showcase';": f"pptx.title = '{name} Branded Showcase';",
        "headFontFace: 'Aptos Display'": f"headFontFace: '{display_font}'",
        "bodyFontFace: 'Aptos'": f"bodyFontFace: '{body_font}'",
        "const OUT = path.join(__dirname, 'exports', 'slides-editorial-pattern-showcase.pptx');": f"const OUT = path.join(__dirname, 'exports', '{name.lower().replace(' ', '-')}-branded-showcase.pptx');",
        "bgWarm: 'F5F1EA'": f"bgWarm: '{bg}'",
        "bgWhite: 'FFFFFF'": f"bgWhite: '{surface}'",
        "surface: 'FCFAF7'": f"surface: '{surface}'",
        "surfaceAlt: 'F3EEE8'": f"surfaceAlt: '{surface_alt}'",
        "textPrimary: '171411'": f"textPrimary: '{text_primary}'",
        "textSecondary: '4B443D'": f"textSecondary: '{text_secondary}'",
        "textSoft: '7A6F66'": f"textSoft: '{text_soft}'",
        "rule: 'D8CEC2'": f"rule: '{rule}'",
        "accent: 'C86432'": f"accent: '{accent}'",
        "accentSoft: 'F3E1D8'": f"accentSoft: '{accent_soft}'",
        "blue: '2E6FD0'": f"blue: '{data_link}'",
    }

    for old, new in replacements.items():
        deck = replace_once(deck, old, new, old)

    deck = replace_once(
        deck,
        "const layoutHelpers = require('../../assets/pptxgenjs_helpers/layout');",
        "const layoutHelpers = require('./pptxgenjs_helpers/layout');",
        "local helper import",
    )

    deck = deck.replace("fontFace: 'Aptos Display'", f"fontFace: '{display_font}'")
    deck = deck.replace("fontFace: 'Aptos'", f"fontFace: '{body_font}'")
    deck = deck.replace("Slides editorial pattern showcase", f"{name} branded showcase")
    deck = deck.replace("Editorial Slide Pattern Showcase", f"{name} Branded Showcase")
    deck = deck.replace("pattern showcase", f"{name.lower()} showcase")

    deck_path.write_text(deck, encoding="utf-8")

    readme_path = output_dir / "README.md"
    if readme_path.exists():
        readme = readme_path.read_text(encoding="utf-8")
        readme = readme.replace("Editorial Pattern Showcase", f"{name} Branded Showcase")
        readme = readme.replace("slides-editorial-pattern-showcase.pptx", f"{name.lower().replace(' ', '-')}-branded-showcase.pptx")
        readme_path.write_text(readme, encoding="utf-8")

    return deck_path


def main() -> int:
    parser = argparse.ArgumentParser(description="Apply brand proposal to sandbox showcase deck.")
    parser.add_argument("proposal_md", help="Path to brand proposal markdown generated by slides_brand_onboarding.py")
    parser.add_argument("--name", default="Brand", help="Brand label used for output naming")
    parser.add_argument("--source", default=str(DEFAULT_SOURCE), help="Source showcase directory")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT), help="Output sandbox showcase directory")
    args = parser.parse_args()

    source_dir = Path(args.source).expanduser().resolve()
    output_dir = Path(args.output).expanduser().resolve()
    proposal_path = Path(args.proposal_md).expanduser().resolve()

    deck_path = apply_brand(source_dir, output_dir, proposal_path, args.name)
    print(f"Applied brand proposal to sandbox deck: {deck_path}")
    print(f"Output directory: {output_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
