Title: Sr. Director, Organizational Projects
Company: Confidential Government
Location: Riyadh, Saudi Arabia (On-site)
Score: 91
URL: https://www.linkedin.com/jobs/view/4413286366/
---JD---
About the job Job Description Develop and implement departmental plans and programs following approval, ensuring alignment with organizational objectives and operational priorities. Coordinate with other administrative units across the organization to facilitate collaboration and ensure the successful delivery of shared initiatives and projects. Establish and oversee the project management methodology while ensuring consistent compliance and implementation across all projects and initiatives. Align projects and initiatives with the organization’s strategic objectives to ensure effective execution and value realization. Manage projects and strategic initiatives, monitor progress against targets, and implement corrective actions when necessary to maintain performance and delivery standards. Supervise the review of project milestones, deliverables, and expenditures to ensure quality, efficiency, and compliance with approved plans and budgets. Enhance and develop the Enterprise Project Management (EPM) system in accordance with the approved methodology and integrate it with the ERP system. Approve Internal Service Level Agreements (SLAs) and evaluate compliance with agreed service standards and performance levels. Assess the performance of portfolio managers and the Head of Project Support, identify development areas, and provide professional guidance and direction. Continuously improve project management methodologies in line with international best practices and ensure organization-wide adherence to established standards. Prepare and issue periodic reports on project and initiative performance, key performance indicators (KPIs), and recommended corrective actions. Develop annual training plans for all employees within the Project Management Office (PMO) to support capability development and operational excellence. Manage organizational risks and challenges in collaboration with the Governance, Compliance, and Risk Management function, ensuring effective mitigation strategies are implemented. Contribute to the development, review, and continuous enhancement of performance indicators related to PMO activities in coordination with the relevant administrative units. Education: Bachelor’s degree in project management, Business Administration, Management or a related field. Experience: Bachelor’s Degree: Minimum of 10 years of experience. Master’s Degree: Minimum of 8 years of experience. PhD: Minimum of 6 years of experience. … more Set alert for similar jobs Sen

NASR_REVIEW_NEEDED
