Title: Head of Business Development
Company: KPay Group
Location: Dubai, United Arab Emirates
Score: 100
URL: https://ae.linkedin.com/jobs/view/head-of-business-development-at-kpay-group-4387226381
---JD---
About Us:KPay Group (“KPay”) is a leading fintech company committed to empowering businesses of all sizes through simple, smart, seamless, and secure technology solutions. Serving over 72,000 merchants across Australia, Hong Kong, Japan, and Singapore, KPay helps unlock growth potential by providing a one-stop platform for financial management, business operations, and digital transformation. In 2024, KPay raised a record-breaking USD 55 million in its Series A funding round—the largest globally in the payments sector that year. The company has since been recognised as PayTech of the Year at the Asia FinTech Awards and named to Forbes Asia’s 100 to Watch list in 2025.
About the Role:As the first business leader on the ground in the UAE, you will architect and execute our go-to-market strategy, build and lead the early BD/sales team, and establish KPay as a trusted partner for UAE merchants. This is a true zero-to-one role: you will shape our market entry, define our sales playbook, cultivate key partnerships, and directly drive early revenue—laying the foundation for scalable growth. If you thrive in building from scratch, excel in high-ambiguous environments, and are motivated by creating something impactful, this is your opportunity.
Job Description:Build & own the UAE GTM strategy – develop and execute the market entry plan, including target segments, pricing approach, partnership roadmap, and sales model tailored to the UAE ecosystem.Lead from the front – personally drive early enterprise and key merchant deals while building, mentoring, and scaling a high-performing BD team.Design & implement sales operations – establish CRM processes, pipeline governance, performance metrics, and incentive frameworks to ensure transparency, velocity, and predictability.Forge strategic partnerships – identify, negotiate, and manage alliances with banks, fintechs, ISVs, and channel partners to accelerate market penetration.Own the revenue number – achieve and exceed quarterly targets for merchant acquisition, transaction volume, and revenue growth.
Job Requirements:12+ years in business development, sales, or GTM roles, with a proven track record of building and scaling revenue in early-stage or high-growth B2B SME environments (fintech, payments, SaaS preferred).Deep understanding of the UAE business landscape – existing network, cultural fluency, and knowledge of local regulations, competitive dynamics, and customer behavior.A builder’s mindset – experience designing sales processes, team structures, and partnership frameworks from scratch, not just managing established pipelines.Strong leadership presence – ability to inspire, coach, and grow a team while remaining hands-on in key deals and strategic conversations.Excellent communication and relationship skills – persuasive in both one-on-one and group settings, able to engage C-level stakeholders and partners with credibility.Resilient and entrepreneurial – thrives in ambiguity, learns quickly, and operates with urgency, integrity, and a merchant-first attitude.NASR_REVIEW_NEEDED
