Title: Arabic Speaking Cyber Security Director - Doha. 12 month contract
Company: Consulting Point
Location: Dubai, United Arab Emirates
Score: 100
URL: https://ae.linkedin.com/jobs/view/arabic-speaking-cyber-security-director-doha-12-month-contract-at-consulting-point-4386334477
---JD---
This is a 12 month full time contract. Fluent Arabic is a must. Immediate start. Location is Doha in Qatar. The 12 month contract could be extended in the future.
As Director, you will lead the design and delivery of end-to-end cybersecurity programmes across government entities, from strategy development through to implementation and operationalisation.
Key responsibilities include:Designing and implementing cybersecurity strategies and roadmaps aligned with government priorities and regulatory frameworksActing as a trusted advisor to senior government leaders, providing strategic guidance on cyber risk, governance and resilienceLeading large, multi-disciplinary delivery teams across strategy, architecture, implementation and operationsOverseeing programmes involving cloud security, OT/IoT security, AI security and digital transformation initiativesEnsuring compliance with government security frameworks and standards such as ISO 27001 and national cybersecurity regulationsManaging programme governance, risk mitigation and quality assurance across complex engagementsMentoring and developing consulting teams while strengthening cybersecurity capability across the organisation
Requirements10+ years of experience in technology and cybersecurity, including direct work with government or public sector organisationsProven leadership delivering large-scale cybersecurity transformationsDeep expertise across cyber strategy, governance, risk management, security architecture, threat intelligence and incident responseStrong experience with cloud security, digital transformation and secure IT modernisationAbility to influence and communicate effectively with senior public sector stakeholders and executivesBachelor’s or Master’s degree in Cyber Security, Computer Science or a related fieldProfessional certifications such as CISSP, CISM, CISA, CRISC, ISO 27001 Lead Auditor or cloud security certificationsNASR_REVIEW_NEEDED
