Title: VP - Engineering (Exchange)
Company: Cronos
Location: Dubai, United Arab Emirates
Score: 54
URL: https://ae.linkedin.com/jobs/view/vp-engineering-exchange-at-cronos-4388679616
---JD---
The OpportunityCronos Labs is building the infrastructure to collapse every speculative market into one app. Tokenized stocks, crypto perpetuals, prediction markets, spot: one balance, every market, powered by Crypto.com's 150M+ users and regulated infrastructure for tokenized equities.
We need a VP- Engineering to build the trading engine that makes this possible. The core technical mandate is a hybrid onchain Central Limit Order Book (CLOB) and matching engine with institutional-grade risk infrastructure: cross-asset margin, real-time liquidation systems, and a risk engine that can handle correlated drawdowns across tokenized stocks and crypto derivatives simultaneously. This is the single biggest capability gap on the team. Our blockchain and platform engineering is well-staffed and capable. What we lack is the person who has built centralized, high-performance trading infrastructure and can translate that expertise into a hybrid onchain architecture.
This is a greenfield build. You are not inheriting someone else's architecture. The Sidecar Sequencer (Rust, off-chain) handles order matching at <5ms P50 latency and 100K OPS throughput. The Cronos EVM handles settlement and custody. You will own the full technical stack from matching engine to smart contracts to mobile app, with the team across Smart Contracts, Blockchain, DevOps, Platform, QA, Trading, and Inventory.
The Product You Are BuildingCronos App is a mobile-first trading app that lets users:Trade tokenized stocks (NVDA, TSLA, etc.) 24/7 with increased buying powerTrade crypto perpetuals and spotTrade sports and event outcomes (prediction markets) with the ability to exit earlyUse one balance to collateralize positions across all asset classesChoose between "Simple/Fun Mode" (guardrails, plain language) and "Pro Mode" (advanced execution, lowest fees)The product is powered by Crypto.com's regulated infrastructure for tokenized equities and prediction markets and built on the Cronos blockchain.
What You'll OwnPrimary Mandate: Trading Infrastructure (The Gap)
Hybrid CLOB & Matching Engine. Architect and ship the off-chain Sidecar Sequencer (Rust) with <5ms P50 tick-to-trade latency, 100K OPS throughput, and <1ms latency variance. Integrate with Cronos EVM for onchain settlement (<60s settlement delay). Route between onchain CLOB and offchain RFQ for best execution.Risk Engine & Margin Systems. Build the full risk stack: collateral weighting, cross-asset netting, initial margin checks, dynamic maintenance thresholds. Unified margin where tokenized equities can margin crypto trades and vice versa. Real-time risk calculations across stocks, crypto, and prediction markets.Liquidation Infrastructure. Design and implement the liquidation engine, auto-deleveraging (ADL) system, and insurance fund architecture. These must survive correlated market crashes, not just normal volatility. The insurance fund must be verifiable onchain with clear deployment rules.Perpetuals & Derivatives Engine. Perpetual futures with funding rate mechanisms, leverage management, and position lifecycle. Phase 1 forks the CDC Exchange matching engine; Phase 2 transitions to a fully onchain Global Order Book.Oracle Integration & Market Data. Manipulation-resistant price feeds for liquidation triggers, mark price computation, and cross-market reference pricing.
Secondary Mandate: Platform & Blockchain Smart Contract & Blockchain Infrastructure. Cronos chain upgrades, USDC migration (IOU to native stablecoin), bridge and cross-chain infrastructure, smart contract security and audit pipeline. Vault, Clearing House, Insurance Fund, and Governance contracts.Platform & Mobile Engineering. Mobile-first consumer app for emerging markets. Embedded wallet with passkey-based authentication. Account abstraction and TEE/verifiable compute for signing. API Gateway and SDK.DevOps & QA. CI/CD, infrastructure reliability, automated testing, performance benchmarking.CDC Integration & Coordination. Coordinate with the Crypto.com tokenization team on shared Confluence/documentation workflows and align timelines across organizations.
What We're Looking ForRequiredDeep trading infrastructure and risk management experience. You have built matching engines, margin systems, liquidation engines, or real-time risk platforms. You understand order matching semantics, cross-collateralization models, and how liquidation cascades propagate under stress. This experience can come from tier-1 investment banks, hedge funds, prop shops, centralized crypto exchanges, or DeFi derivatives protocols.Derivatives market structure fluency. Perpetuals, options, funding rates, mark price computation, portfolio margin. You don't just understand the theory. You've built systems that handle these instruments at production scale.Hands-on blockchain/DeFi depth or proven ability to ramp fast. EVM smart contracts (Solidity), protocol design, bridge security, token standards. If you're crossing over from TradFi, you need to demonstraNASR_REVIEW_NEEDED
