Title: Project Director
Company: AKQA
Location: Dubai, United Arab Emirates
Score: 100
URL: https://ae.linkedin.com/jobs/view/project-director-at-akqa-4387261351
---JD---
At AKQA (part of WPP), we believe in the imaginative application of art and science to create beautiful ideas, products and services. With an entrepreneurial and collaborative approach, we design adaptive digital services and applications that capture the imagination, delivering impressive returns for our clients.

The Delivery team are at the epicentre of all projects, ensuring they’re delivered to the highest quality, on time, and that clients receive the greatest possible value from their investment

From our location in Dubai, AKQA offers our staff the opportunity to produce meaningful and award-winning work for world-class clients and brands. You will work in an environment which fosters a meritocratic culture and encourages ownership, you’ll be liaising with bright minds across KSA, UAE and Egypt. You’ll have the opportunity to learn and grow within a creative and innovative. team, with access to ongoing personal and professional development. At AKQA, we’re committed to your career growth, as well as your work/life balance.

As a Project Director at AKQA, you will be responsible for the overall direction and management of projects exceeding £1.5m, either independently or through designated Project Managers where appropriate. You will ensure consistency with corporate strategy, processes and client satisfaction. These projects should be delivered on time, on budget, to a high level of quality but importantly to achieve the established project success criteria and exceed client expectations.

Role Requirements

Responsible for the successful delivery of highly complex projects with revenue typically in excess of £1.5m across large-scale project or multiple projectsAnalyses and understands the project and its context within the client's business and how expected benefits can be enabled (indirect, direct, financial and non-financial.Structure projects appropriately from the outset, selecting the best tools and processes to meet the project, team and client requirements.Identify project risks and issues, ensuring effective mitigation and risk strategies are implemented.Estimate and prepare strong proposals. Track and report financial status of projects against an agreed budget, using burn reports to monitor and proactively mitigate potential overruns, highlighting clearly to the Executive Delivery Director when an overrun is likely to occur.Identify and successfully manage multiple suppliers, partners and senior clients expected to be at C level to ensure the best outcome for both clients and AKQA. Keep stakeholders informed of project progress at all times and manage expectations proactively. Work with Client Leads on delivering high scoring client satisfaction. Develop positive senior level relationships both internally and externally.Take an active role in new business pitches.Varying project methodologies along with their pros and cons. Able to strike a balance between pragmatic project delivery practices and by-the-book, ‘ideal scenario’ delivery.Support the Executive Delivery Director in the recruitment, retention, review, motivation, training and mentoring of the Delivery team. Develop and deliver internal training courses. Contribute to the improvement of processes.

QUALITIES AND CHARACTERISTICS

Project management experience within the digital/creative industry.Experience of project managing custom-designed, highly-complex full life-cycle projects in excess of £1.5m.Delivery of distributed development projects across multiple geographies is advantageous.Strong knowledge and best practice approach for project management.Experience of having adapted the delivery process around those required by a client.Enough knowledge of SCRUM, DSDM, Kanban and Lean to have a debate with clients as to their merits and drawbacks.Exceptional client management skills.Strong organisational and planning skills.Excellent communication skills across all mediums – presentation, verbal, written; gaining the confidence of the business; credible and experienced at operating at C level.Ability to build excellent relationships with peers and business counterparts, and the ability to achieve results under potentially difficult circumstances. Negotiates well, listens actively and makes compelling points.Experience of mentoring and coaching.Displays creative approach to problem-solving and project management in general.Demonstrates excellent levels of quality and attention to detail.Ability to make sound commercial and financial decisions, quickly understand problems, propose solutions and manage customer situations.Ability to work well under pressure and to have an objective focused and positive approach, and be comfortable working independently, be self-motivated and self-driven.Strong customer service ethos, a commitment to quality and the will to constantly drive improvements. Commitment to high standards of excellence and integrity.Possess good business acumen and sound judgement. Be entrepreneurial, with a collaborative, sNASR_REVIEW_NEEDED
