#!/usr/bin/env python3
"""
Dream Cycle - Nightly Memory Optimization
==========================================

This script runs nightly to:
1. Archive old session files
2. Optimize agents.md size
3. Clean up memory files
4. Generate dream report

Usage:
    python dream_cycle.py [--dry-run] [--verbose]
"""

import os
import json
import shutil
from datetime import datetime, timedelta
from pathlib import Path

# Configuration
WORKSPACE = Path("/root/.openclaw/workspace")
MEMORY = WORKSPACE / "memory"
SESSIONS_DIR = MEMORY / "sessions"
PROJECTS_DIR = MEMORY / "projects"
REFERENCE_DIR = MEMORY / "reference"
ARCHIVE_DIR = MEMORY / "archive"

# Settings
KEEP_DAYS = 7  # Keep last 7 days in active memory
AGENTS_MD_TARGET = 600  # Target tokens for agents.md
MEMORY_MD_TARGET = 1000  # Target tokens for memory.md


def count_tokens(text):
    """Rough token estimate (4 chars per token average)"""
    return len(text) // 4


def get_file_size(path):
    """Get file size in bytes"""
    if path.exists():
        return path.stat().st_size
    return 0


def find_old_sessions():
    """Find session files older than KEEP_DAYS"""
    old_files = []
    
    # Check workspace root for .md files
    for f in WORKSPACE.glob("*.md"):
        if f.stat().st_mtime < (datetime.now() - timedelta(days=KEEP_DAYS)).timestamp():
            # Skip core files
            if f.name not in ["MEMORY.md", "IDENTITY.md", "USER.md", "SOUL.md", "AGENTS.md"]:
                old_files.append(f)
    
    return old_files


def archive_sessions(files, dry_run=False):
    """Archive old session files"""
    archived = []
    target_dir = SESSIONS_DIR / datetime.now().strftime("%Y-%m")
    target_dir.mkdir(parents=True, exist_ok=True)
    
    for f in files:
        if dry_run:
            print(f"  [DRY-RUN] Would archive: {f.name}")
        else:
            shutil.move(str(f), str(target_dir / f.name))
            archived.append(f.name)
    
    return archived


def optimize_agents_md():
    """Optimize agents.md size"""
    agents_file = WORKSPACE / "AGENTS.md"
    
    if not agents_file.exists():
        return {"status": "skip", "reason": "File not found"}
    
    with open(agents_file) as f:
        content = f.read()
    
    current_tokens = count_tokens(content)
    
    if current_tokens <= AGENTS_MD_TARGET:
        return {
            "status": "ok",
            "tokens": current_tokens,
            "target": AGENTS_MD_TARGET
        }
    
    # TODO: Implement intelligent summarization
    # For now, just report the issue
    return {
        "status": "warning",
        "tokens": current_tokens,
        "target": AGENTS_MD_TARGET,
        "action_needed": "Manual review recommended"
    }


def clean_memory_files():
    """Clean up memory directory"""
    cleaned = []
    
    # Find files that should be moved
    for f in MEMORY.glob("*.md"):
        if f.stat().st_mtime < (datetime.now() - timedelta(days=30)).timestamp():
            if f.name.startswith("20"):  # Date-based files
                target = ARCHIVE_DIR / f.name[:7]  # YYYY-MM
                target.mkdir(parents=True, exist_ok=True)
                shutil.move(str(f), str(target / f.name))
                cleaned.append(f.name)
    
    return cleaned


def generate_dream_report(archived, cleaned, agents_status):
    """Generate dream report for Morning Brief"""
    report = f"""# Dream Report - {datetime.now().strftime('%Y-%m-%d')}

## Summary
- Sessions archived: {len(archived)}
- Files cleaned: {len(cleaned)}
- Agents.md status: {agents_status['status']}

## Details
### Archived Sessions
"""
    
    if archived:
        for f in archived:
            report += f"- {f}\n"
    else:
        report += "- None\n"
    
    report += "\n### Cleaned Files\n"
    if cleaned:
        for f in cleaned:
            report += f"- {f}\n"
    else:
        report += "- None\n"
    
    report += f"""
## Agents.md Status
- Current tokens: {agents_status.get('tokens', 'N/A')}
- Target: {AGENTS_MD_TARGET}
- Status: {agents_status['status']}

## Recommendations
"""
    
    if agents_status['status'] == 'warning':
        report += "- Review AGENTS.md for bloat\n"
    
    report += "- Continue executing weekly priorities\n"
    
    report += f"""
---
*Generated by Dream Cycle at {datetime.now().isoformat()}*
"""
    
    report_file = MEMORY / f"dream-report-{datetime.now().strftime('%Y-%m-%d')}.md"
    
    with open(report_file, 'w') as f:
        f.write(report)
    
    return str(report_file)


def run_dream_cycle(dry_run=False, verbose=False):
    """Execute full Dream Cycle"""
    
    print(f"🌙 Dream Cycle started at {datetime.now().isoformat()}")
    
    # Step 1: Find old sessions
    if verbose:
        print("\n1. Finding old sessions...")
    old_sessions = find_old_sessions()
    print(f"   Found {len(old_sessions)} old session files")
    
    # Step 2: Archive sessions
    if verbose:
        print("\n2. Archiving sessions...")
    archived = archive_sessions(old_sessions, dry_run=dry_run)
    print(f"   Archived {len(archived)} files")
    
    # Step 3: Optimize agents.md
    if verbose:
        print("\n3. Optimizing agents.md...")
    agents_status = optimize_agents_md()
    print(f"   Status: {agents_status['status']} ({agents_status.get('tokens', 'N/A')} tokens)")
    
    # Step 4: Clean memory files
    if verbose:
        print("\n4. Cleaning memory files...")
    cleaned = clean_memory_files()
    print(f"   Cleaned {len(cleaned)} files")
    
    # Step 5: Generate report
    if verbose:
        print("\n5. Generating dream report...")
    report_file = generate_dream_report(archived, cleaned, agents_status)
    print(f"   Report: {report_file}")
    
    print(f"\n✅ Dream Cycle complete!")


if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="Dream Cycle - Nightly Memory Optimization")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be done")
    parser.add_argument("--verbose", "-v", action="store_true", help="Verbose output")
    
    args = parser.parse_args()
    
    run_dream_cycle(dry_run=args.dry_run, verbose=args.verbose)
